### ISSUE TITLE
[FEATURE] Configurations for planners comparison experiment

### ISSUE THREAD

**Issue by yaacovpariente** [yaacovpariente/POMDPPlanners#41]
# Create Configuration System for Planners Comparison Experiments

## Is your feature request related to a problem? Please describe.
Currently, comparing different POMDP planners (like PFT-DPW) requires manually setting up experiment configurations, which is error-prone and makes it difficult to reproduce results. There's no standardized way to:
- Define experiment parameters
- Log and compare results across different planners
- Save and load experiment configurations
- Generate consistent reports

## Describe the solution you'd like
I propose creating a configuration system that would:

1. **Configuration Structure**
   - Create a YAML/JSON-based configuration system for defining experiments
   - Support hierarchical configurations (base configs with overrides)
   - Include validation for required parameters

2. **Planner Configurations**
   ```yaml
   planners:
     pft_dpw:
       base_config:
         discount_factor: 0.95
         depth: 10
         k_a: 1.0
         alpha_a: 0.5
         k_o: 1.0
         alpha_o: 0.5
         exploration_constant: 1.0
         time_out_in_seconds: 60
         n_simulations: 1000
         min_samples_per_node: 10
         min_visit_count_per_action: 1
   ```

3. **Experiment Runner**
   - Create an experiment runner class that:
     - Loads configurations
     - Initializes planners with specified parameters
     - Runs experiments in parallel
     - Collects and aggregates results

4. **Results Management**
   - Implement a results storage system
   - Generate comparison plots and tables
   - Export results in standard formats (CSV, JSON)
   - Create experiment reports

5. **Command Line Interface**
   ```bash
   python run_experiment.py --config experiments/planner_comparison.yaml --output results/
   ```

## Describe alternatives you've considered
1. **Hard-coded Configurations**
   - Pros: Simple to implement
   - Cons: Not flexible, hard to maintain, difficult to share

2. **Database-driven Configuration**
   - Pros: Centralized storage, version control
   - Cons: Overkill for simple experiments, adds complexity

3. **Environment Variables**
   - Pros: Easy to modify
   - Cons: Not structured, hard to version control

## Additional context
- The current implementation in `pft_dpw.py` shows the need for a more structured way to handle planner parameters
- This would help in:
  - Comparing different MCTS variants
  - Benchmarking against other POMDP solvers
  - Reproducing research results
  - Sharing experiment setups with the community

**Priority**: High
**Labels**: enhancement, configuration, experiments
**Milestone**: v1.0.0
